FROM node:13.12.0-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

# COPY node_modules . no need to copy node_modules
COPY public .
COPY src .

CMD ["npm", "start"]