FROM python:latest

WORKDIR /code

COPY nlp_api ./
COPY requirements.txt ./

RUN pip install -r requirements.txt

CMD [ "uvicorn", "nlp_api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]